FROM rocker/rstudio:3.6.1
MAINTAINER "David Novak"

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion

RUN apt-get update \
    && apt-get install -y\
    python3 \
    python3-pip \
    valgrind \
    python2.7 \
    python-pip

RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-5.3.0-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

RUN apt-get update \
    && apt-get install\
    zlib1g-dev

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    Rhdf5lib \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN apt-get update \
    && apt-get install -y\
    libxml2-dev


RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    ncdfFlow \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    XML \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    CytoML\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    flowWorkspace\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    flowCore\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    tidyverse\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    Rtsne\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    uwot\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/data/experiment" \
    ALL\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    ConsensusClusterPlus\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    FlowSOM\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN apt-get update \
    && apt-get install -y\
    libgeos-dev

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    rgeos\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    flowDensity\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    flowAI\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    RColorBrewer\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    cowplot\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    gplots\
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    scales \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    reticulate \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN apt-get update \
    && apt-get install -y\
    libgmp3-dev\
    libmpfr-dev


RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    devtools 

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    roxygen2 \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds


RUN conda remove --name tidycell_cellcnn_env --all
RUN conda create --name tidycell_cellcnn_env python=2.7

RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda activate tidycell_cellcnn_env  && \
    pip install -r https://raw.githubusercontent.com/eiriniar/CellCnn/master/requirements.txt &&\
    pip install git+https://github.com/eiriniar/CellCnn.git


RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    pheatmap \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN echo "PATH=$PATH:/usr.local/bin" >> /usr/local/lib/R/etc/Renviron.site

COPY scripts /home/rstudio/tidycell/scripts
COPY raa.R /home/rstudio/tidycell/raa.R
COPY run_aberrance_analysis.sh /home/rstudio/tidycell/run_aberrance_analysis.sh

RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    -r "http://www.bioconductor.org/packages/release/bioc" \
    EmbedSOM \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds
